const list = [
  {
    id: 0,
    verified: true,
    name: '박새로이',
    gender: 'male',
    age: 30,
    location: '서울특별시',
    fromMe: '5.4km',
    description: '제가 원하는건 자유입니다. 누구도 저와 제 사람들을 건들지 못하도록 제 말 행동에 힘이 실리고, 어떤 부당함도, 누군가에게도 휘둘리지 않는제 삶의 주체가 저인게 당연한소신의 대가가 없는 그런 삶을 살고 싶습니다.',
    info: {
      height: 182,
      fit: '보통',
      work: '자영업',
      education: '고등학교',
      educationPlace: null,
      personality: ['주도적인', '섬세함', '다정함'],
      religion: null,
      drinking: '가끔',
      smoking: null,
      bloodType: 'AB',
      constellation: '물병',
    },
    photos: ['https://yt3.ggpht.com/Db1MasghwoY-pcQIqrJ0f3tX2e7WQ8nuwdyhd1W6zw4zHDFuVyrFA_MgOWxhYfuWS8Byue_y=s900-c-k-c0x00ffffff-no-rj', 'https://post-phinf.pstatic.net/MjAyMjA1MTZfMTAy/MDAxNjUyNjkyMTA4Mjc5.ew3jLAJpdQDZW4sdlXxQHPI3frkb7LSCUJE-Qkx6x0Yg.DE3__RjuVGXomUjk9M_Pu0wHpUF0YaGnsrRUQs3wSaUg.JPEG/%EB%B0%95%EC%86%8C%EC%A4%80_%ED%99%94%EB%B3%B4_%EC%8B%9C%EC%9E%91%ED%95%A9%EB%8B%88%EB%8B%A4.jpg?type=w1200', 'https://mblogthumb-phinf.pstatic.net/MjAyMDAxMjhfMjc5/MDAxNTgwMjA4MDc4MzIy.0orhMlIHOJYwxy5oXWiws8pPOGfAN7a5wMqtsIq9Nkgg.afsZip2glSShvLVuETYGaqUppAEPRgDPYNwnTYl-_EEg.JPEG.chanlan/20200128_%EB%B0%95%EC%84%9C%EC%A4%80_1.jpg?type=w800'],
    strength: ['허세 없어요', '뭐든 잘 먹어요', '솔직해요', '예의가 발라요'],
    interest: ['스포츠/운동', '여행', '요리', '자기계발', '재테크', '노래부르기'],
  },
  {
    id: 1,
    verified: true,
    name: '커피프린스',
    gender: 'male',
    age: 43,
    location: '서울특별시',
    fromMe: '11km',
    description: '너 좋아해. 네가 남자건 외계인이건 이제 상관 안 해. 가보자, 갈 데까지.',
    info: {
      height: 185,
      fit: '보통',
      work: '자영업',
      education: '대학교',
      educationPlace: null,
      personality: ['주도적인', '섬세함', '다정함'],
      religion: null,
      drinking: '가끔',
      smoking: null,
      bloodType: 'B',
      constellation: '황소',
    },
    photos: ['https://t1.daumcdn.net/cfile/tistory/99E4E43359E8B3C621', 'https://i.pinimg.com/originals/2f/45/ab/2f45ab622787b48a7ffd348516f162dd.jpg', 'https://img.vogue.co.kr/vogue/2019/09/style_5d6f22585f074-930x619.png', 'http://woman.chosun.com/news/photo/202207/100975_89566_4355.jpg', 'https://www.thedailypost.kr/news/photo/old/qBFlA.jpg'],
    strength: ['뛰어난 커리어','쌍커풀 없는 눈', '워커홀릭', '운동을 좋아해요', '유머 감각이 있어요', '장난기가 많아요', '비율이 좋아요'],
    interest: ['스포츠/운동', '독서', '자기계발', '요리', '외국어/어학'],
  },
  {
    id: 2,
    verified: false,
    name: 'Jay Park',
    gender: 'male',
    age: 35,
    location: '서울특별시',
    fromMe: '4.1km',
    description: '길거리를 걷다 보면 사랑 노래만 흘러나와 나는 왜 저런 게 낯설까 난 한국말까지 서툴러',
    info: {
      height: 174,
      fit: '슬림 근육',
      work: '방송 관련직',
      education: '고등학교',
      educationPlace: null,
      personality: ['주도적인', '털털한', '도발적인'],
      religion: '천주교',
      drinking: '자주',
      smoking: '가끔',
      bloodType: 'AB',
      constellation: '처녀',
    },
    photos: ['http://newsimg.hankookilbo.com/2019/07/01/201907011522723193_1.jpg', 'https://img.etoday.co.kr/pto_db/2021/12/20211231211853_1703470_693_872.jpg'],
    strength: ['높은 경제력', '체력이 좋아요', '운동을 좋아해요'],
    interest: ['스포츠/운동', '드라이브', '음악 듣기', '재테크'],
  },
  {
    id: 3,
    verified: false,
    name: '정해인',
    gender: 'male',
    age: 33,
    location: '서울특별시',
    fromMe: '7.6km',
    description: '밥 잘 사주는 예쁜 누나 없나요~',
    info: {
      height: 186,
      fit: '슬림',
      work: 'IT 관련직',
      education: '대학교',
      educationPlace: '가상 대학교',
      personality: ['정직한', '조용한', '친절한'],
      religion: '불교',
      drinking: '자주',
      smoking: null,
      bloodType: 'AB',
      constellation: '황소',
    },
    photos: ['https://photo.jtbc.co.kr/news/2018/03/07/201803071002543711.jpg', 'http://talkimg.imbc.com/TVianUpload/TVian/TViews/image/2018/02/26/xzayycgxzko6636552321499649475.png', 'https://newsimg.sedaily.com/2018/04/01/1RY35YLKP9_1.jpg', 'https://cdn.topstarnews.net/news/photo/201803/380884_25538_1639.jpg'],
    strength: ['한 사람만 봐요', '시사에 밝아요', '오똑한 콧날', '게임을 잘해요', '동안이에요'],
    interest: ['산책하기', '음악 듣기', '노래 부르기', 'IT'],
  },
  {
    id: 4,
    verified: false,
    name: '백이진',
    gender: 'male',
    age: 38,
    location: '시흥시',
    fromMe: '21.6km',
    description: '열여덟, 우리는 서로의 이름을 처음 불렀다. 그리고 스물 하나, 우린 사랑을 했다.',
    info: {
      height: 188,
      fit: '슬림',
      work: '방송 관련직',
      education: '고등학교',
      educationPlace: null,
      personality: ['정직한', '다정한', '친절한'],
      religion: null,
      drinking: '자주',
      smoking: null,
      bloodType: 'A',
      constellation: '게',
    },
    photos: ['https://www.jeonmae.co.kr/news/photo/202206/896923_588697_2015.jpeg', 'https://blog.kakaocdn.net/dn/WdnHl/btrFkwTbVpd/qhVp3YWVLAoCn8OI2oSnHK/img.jpg', 'http://res.heraldm.com/content/image/2022/06/20/20220620000819_0.jpg', 'https://m.upinews.kr/data/upi/image/20181218/p1065572742751393_423_thum.jpg', 'https://img.wkorea.com/w/2021/02/style_60179ace176ee-561x700.jpeg'],
    strength: ['한 사람만 봐요', '쌍커풀 없는 눈', '오똑한 콧날', '워커홀릭'],
    interest: ['산책하기', '음악 듣기', '노래 부르기', '드라이브', '재테크'],
  },
];

export default function handler(req, res) {
  if(req.query.id === 'null'){
    res.status(200).json({data: list});
  }else{
    res.status(200).json({data: list[Number(req.query.id)]});
  }
}
